### PR TITLE
 ignored django admin app to check for type safety

### PR DESCRIPTION
**Pull request by nightboard**
Hi, can you review the code please if it is safe to push or if I have used any bad practices in the code? I have ignored that the `admin` app returned an empty `list` instead so it will not show a warning for that.

### CODE REVIEW

**Comment by AliSayyah** [comment]
Thank you. It would be better if the exclusion was a little more dynamic.
Check out my last comment in the issue.

**Comment by nightboard** [comment]
@AliSayyah Oh yes but I think the `admin`  app will never be typesafe unless Django itself adds types in that view so can we ignore this for all times and implement your new idea as a separate feature?

**Comment by AliSayyah** [comment]
@nightboard Hey there!
I'm back from vacation.
Yeah, that works too.

**Comment by AliSayyah** [comment]
We will need a new unit test for this scenario. If you want, I can do it.

**Comment by nightboard** [comment]
Do you mean we have to add a `unit` test for this PR?

**Comment by AliSayyah** [comment]
> Do you mean we have to add a `unit` test for this PR?

Yes, that's correct.

**Comment by nightboard** [comment]
@AliSayyah Yeah no problem I can write a unit test can you just guide me a little I mean I have to count no. of warnings and that will be asserted to `0`  right if we ignored `admin` app and there is no error in the other `apps`.

**Comment by AliSayyah** [comment]
Thank you.
Yeah, that's correct.
There are a few unit tests available in the repository. You can check them out for more information. 
We have a few `urlConf` files available for testing, and we can add new ones based on new scenarios. While testing, we use them as our main URL conf module for checking.
You can create a new one for this PR with `admin` available in the paths. Then you can easily assert the outputs.
If you have any problems, please ask me.

**Comment by nightboard** [comment]
Hi @AliSayyah I have added unit test can you please review it?

**Comment by AliSayyah** [comment]
@nightboard Thank you for this!
I'll merge it after I fix this dependency issue caused by click and typer.

**Comment by AliSayyah** [comment]
@nightboard Can you please rebase this branch on `main`?

**Comment by nightboard** [comment]
@AliSayyah you mean merge this branch in `main` right and then send a pull request? sorry I have no experience with `rebase` can you just point me out any helpful article or hint, please.

**Pull request closed without merging**
